# Generated by Django 4.2.15 on 2024-09-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, verbose_name=True)),
                ("user_name", models.CharField(max_length=20)),
                ("user_password", models.CharField(max_length=20)),
            ],
        ),
    ]
